/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2017-10-31 18:19:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.sql.*;
import com.Connections.*;

public final class AdminResponse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Metamorphosis Design Free Css Templates</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<link href=\"styles.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"nivo-slider.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write(" ");
  PreparedStatement ps = null;
 	ResultSet resultSet= null;
Statement st=null;
PreparedStatement ps1 = null;
	ResultSet resultSet1= null;
Statement st1=null;
String query=null;

      out.write("\r\n");
      out.write("\r\n");
 HttpSession session1=request.getSession(false);  
String n=(String)session.getAttribute("uname");   
      out.write("\r\n");
      out.write("<div id=\"bg_clouds\">\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("<!-- header begins -->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("    \r\n");
      out.write("\t<div id=\"buttons\">\r\n");
      out.write("      <a href=\"index.html\" class=\"but but_t\"  title=\"\">Home</a>\r\n");
      out.write("      <a href=\"admin.html\" class=\"but\" title=\"\">Admin</a>\r\n");
      out.write("     \r\n");
      out.write("      <a href=\"about_us.html\"  class=\"but\" title=\"\">About us</a>\r\n");
      out.write("      <a href=\"contact_us.html\" class=\"but\" title=\"\">Contact us</a>\r\n");
      out.write("       <a href=\"index.html\"  class=\"but\" title=\"\">Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"logo\">\r\n");
      out.write("    \t<a href=\"#\"><font color=\"yellow\" size=5><b>VIT File Transfer</b></font></a>\r\n");
      out.write("      \t<h2><a href=\"#\" id=\"metamorph\">CLOUD STORAGE </a></h2>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("<!-- header ends -->\r\n");
      out.write("<div class=\"top_top\"></div>\r\n");
      out.write("<div class=\"top\">\r\n");
      out.write("\r\n");
      out.write(" <div id=\"wrapper\">\r\n");
      out.write("        <div id=\"slider-wrapper\">        \r\n");
      out.write("            <div id=\"slider\" class=\"nivoSlider\">\r\n");
      out.write("                <img src=\"images/top.jpg\" alt=\"\" />\r\n");
      out.write("                <img src=\"images/top2.jpg\" alt=\"\"/>\r\n");
      out.write("                <img src=\"images/top3.jpg\" alt=\"\" />\r\n");
      out.write("            </div>        \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"lib/jquery-1.4.3.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"lib/jquery.nivo.slider.pack.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(window).load(function() {\r\n");
      out.write("        $('#slider').nivoSlider();\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"top_bot\"></div>\r\n");
      out.write("<div style=\"height:17px\"></div>\r\n");
      out.write("        <!-- content begins -->\r\n");
      out.write("        \t\t<div class=\"cont_top\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <div class=\"line1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col1\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t");

		
		String parameter = request.getParameter("returnParameter");
		if("adminResponse".equalsIgnoreCase(parameter)  ){
			String fileKey = request.getParameter("fileKey");
			String officeId =request.getParameter("officeId");
			String status ="Y";
			query="UPDATE adminupload SET status='"+status+"' where filekey='"+fileKey+"' and office_id='"+officeId+"'";
			ps1=Connections.con().prepareStatement(query);
			ps1.executeUpdate();
		
		
		
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t<h1>Admin response has been submitted sucessfully</h1>\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

		}
			
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h2>File List ");
      out.print(n );
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wrapper pad_bot3\">\r\n");
      out.write("\t\t\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t\t\t<center> User Reqested Files\r\n");
      out.write("\t\t\t\t\t<table  border=\"2\" bordercolor=\"gray\" width=\"500\"  >\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr bgcolor=\"yellow\">\r\n");
      out.write("\t\t\t\t\t<td><center>Name/Key</center></td><td><center>File</center></td><td><center>Permission</center></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");

		int total=0;
			
				query="select status from attacker where owner_id='"+n+"'";
				ps1=Connections.con().prepareStatement(query);
				resultSet1=ps1.executeQuery();
				resultSet1.absolute(1);
				String result=resultSet1.getString(1);
				
				if(result.equals("attack"))
				{
					response.sendRedirect("attacked.jsp");
				}
				
				else
				{
					String status = "R";
				String q="select name,path,filekey,  status, office_id from adminupload where office_id='"+n+"' and status='"+status+"'";
				ps=Connections.con().prepareStatement(q);
				resultSet=ps.executeQuery();
				while(resultSet.next())
				{
					
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr bgcolor=\"white\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td>");
      out.print(resultSet.getString(3));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(resultSet.getString(1));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<!-- \t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"myFunction('");
      out.print(resultSet.getString(1));
      out.write("')\" value=\"OPEN\"></input>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t -->\t\r\n");
      out.write("\t\t\t\t\t<td><a href=\"AdminResponse.jsp?fileKey=");
      out.print(resultSet.getString(3));
      out.write("&officeId=");
      out.print(resultSet.getString(5));
      out.write("&returnParameter=adminResponse\"  title=\"Click here to reponse\"><center>Accept Request</center></a></td>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
 
				}
				}
			
		
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<a href=\"admin_view.jsp\"  title=\"Click here to reponse\"><center>Back</center></a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- content ends --> \r\n");
      out.write("    <!-- bottom begin -->\r\n");
      out.write("\r\n");
      out.write("<!-- bottom end --> \r\n");
      out.write("<!-- footer begins -->\r\n");
      out.write("         \r\n");
      out.write("        <!-- footer ends -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
