/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2017-11-01 03:59:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.sql.*;
import com.Connections.*;

public final class admin_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Metamorphosis Design Free Css Templates</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<link href=\"styles.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"nivo-slider.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("<style>\r\n");
      out.write(".switch {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  width: 60px;\r\n");
      out.write("  height: 34px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".switch input {display:none;}\r\n");
      out.write("\r\n");
      out.write(".slider {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  background-color: #ccc;\r\n");
      out.write("  -webkit-transition: .4s;\r\n");
      out.write("  transition: .4s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider:before {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  height: 26px;\r\n");
      out.write("  width: 26px;\r\n");
      out.write("  left: 4px;\r\n");
      out.write("  bottom: 4px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  -webkit-transition: .4s;\r\n");
      out.write("  transition: .4s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:checked + .slider {\r\n");
      out.write("  background-color: #2196F3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:focus + .slider {\r\n");
      out.write("  box-shadow: 0 0 1px #2196F3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:checked + .slider:before {\r\n");
      out.write("  -webkit-transform: translateX(26px);\r\n");
      out.write("  -ms-transform: translateX(26px);\r\n");
      out.write("  transform: translateX(26px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Rounded sliders */\r\n");
      out.write(".slider.round {\r\n");
      out.write("  border-radius: 34px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider.round:before {\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script >\r\n");
      out.write("\r\n");
      out.write("function changeSecurityCheck(htmlObj){\r\n");
      out.write("\tvar securityCheck = htmlObj.is(\":checked\") ? \"ON\" : \"OFF\";\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t   url: 'securityCheck',\r\n");
      out.write("\t\t   data: {\r\n");
      out.write("\t\t      securityCheck : securityCheck,\r\n");
      out.write("\t\t      fileKey : htmlObj.attr(\"alt\")\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t   },\r\n");
      out.write("\t\t   error: function() {\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\t   },\r\n");
      out.write("\t\t   dataType: 'json',\r\n");
      out.write("\t\t   success: function(data) {\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\t   },\r\n");
      out.write("\t\t   type: 'GET'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write(" ");
  PreparedStatement ps = null;
 	ResultSet resultSet= null;
Statement st=null;
PreparedStatement ps1 = null;
	ResultSet resultSet1= null;
Statement st1=null;
String query=null;

      out.write("\r\n");
      out.write("\r\n");
 HttpSession session1=request.getSession(false);  
String n=(String)session.getAttribute("uname");   
      out.write("\r\n");
      out.write("<div id=\"bg_clouds\">\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("<!-- header begins -->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("    \r\n");
      out.write("\t<div id=\"buttons\">\r\n");
      out.write("      <a href=\"index.html\" class=\"but but_t\"  title=\"\">Home</a>\r\n");
      out.write("      <a href=\"admin.html\" class=\"but\" title=\"\">Admin</a>\r\n");
      out.write("     \r\n");
      out.write("      <a href=\"about_us.html\"  class=\"but\" title=\"\">About us</a>\r\n");
      out.write("      <a href=\"contact_us.html\" class=\"but\" title=\"\">Contact us</a>\r\n");
      out.write("       <a href=\"index.html\"  class=\"but\" title=\"\">Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"logo\">\r\n");
      out.write("    \t<a href=\"#\"><font color=\"yellow\" size=5><b>VIT File Transfer</b></font></a>\r\n");
      out.write("      \t<h2><a href=\"#\" id=\"metamorph\">CLOUD STORAGE </a></h2>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("<!-- header ends -->\r\n");
      out.write("<div class=\"top_top\"></div>\r\n");
      out.write("<div class=\"top\">\r\n");
      out.write("\r\n");
      out.write(" <div id=\"wrapper\">\r\n");
      out.write("        <div id=\"slider-wrapper\">        \r\n");
      out.write("            <div id=\"slider\" class=\"nivoSlider\">\r\n");
      out.write("                <img src=\"images/top.jpg\" alt=\"\" />\r\n");
      out.write("                <img src=\"images/top2.jpg\" alt=\"\"/>\r\n");
      out.write("                <img src=\"images/top3.jpg\" alt=\"\" />\r\n");
      out.write("            </div>        \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"lib/jquery-1.4.3.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"lib/jquery.nivo.slider.pack.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(window).load(function() {\r\n");
      out.write("        $('#slider').nivoSlider();\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"top_bot\"></div>\r\n");
      out.write("<div style=\"height:17px\"></div>\r\n");
      out.write("        <!-- content begins -->\r\n");
      out.write("        \t\t<div class=\"cont_top\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <div class=\"line1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col1\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h2>File List ");
      out.print(n );
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wrapper pad_bot3\">\r\n");
      out.write("\t\t\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t\t\t<center> Admin Files\r\n");
      out.write("\t\t\t\t\t<table  border=\"2\" bordercolor=\"gray\" width=\"500\"  >\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr bgcolor=\"yellow\">\r\n");
      out.write("\t\t\t\t\t<td><center>Name/Key</center></td><td><center>File</center></td><td><center>Permission</center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>Security Check</center></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");

		int total=0;
			
				query="select status from attacker where owner_id='"+n+"'";
				ps1=Connections.con().prepareStatement(query);
				resultSet1=ps1.executeQuery();
				resultSet1.absolute(1);
				String result=resultSet1.getString(1);
				
				if(result.equals("attack"))
				{
					response.sendRedirect("attacked.jsp");
				}
				
				else
				{
				String q="select name,path,filekey, security_check, status from adminupload where office_id='"+n+"'";
				ps=Connections.con().prepareStatement(q);
				resultSet=ps.executeQuery();
				while(resultSet.next())
				{
					
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr bgcolor=\"white\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td>");
      out.print(resultSet.getString(3));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(resultSet.getString(1));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<!-- \t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"myFunction('");
      out.print(resultSet.getString(1));
      out.write("')\" value=\"OPEN\"></input>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t -->\t\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t  ");

				 if(resultSet.getString(5).equals("A")){
				 
      out.write("\r\n");
      out.write("\t\t\t\t <td><center>Attacked</center></td>\r\n");
      out.write("\t\t\t\t ");

				 }else{
				 
      out.write("\r\n");
      out.write("\t\t\t\t \t\r\n");
      out.write("\t\t\t\t\t<td><a href=\"Files/all content/");
      out.print(resultSet.getString(1));
      out.write("\" target='_blank' title=\"Click here to Download\"><center>OPEN</center></a></td>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t");

				 }
			
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<label class=\"switch\">\r\n");
      out.write("  <input type=\"checkbox\" alt=\"");
      out.print(resultSet.getString(3));
      out.write("\" onchange=\"changeSecurityCheck($(this))\"   ");
      out.print(resultSet.getBoolean(4) ? "checked" : "");
      out.write(">\r\n");
      out.write("  <span class=\"slider round\"></span>\r\n");
      out.write("</label>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
 
				}
				}
			
		
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t<center>User Files\r\n");
      out.write("\t\t\t\t\t<table  border=\"2\" bordercolor=\"gray\" width=\"500\"  >\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr bgcolor=\"yellow\">\r\n");
      out.write("\t\t\t\t\t<td><center>Name/Key</center></td><td><center>User_ID</center></td><td><center>File</center></td><td><center>Permission</center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>Security Check</center></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");

		int total1=0;
			
				query="select status from attacker where owner_id='"+n+"'";
				ps1=Connections.con().prepareStatement(query);
				resultSet1=ps1.executeQuery();
				resultSet1.absolute(1);
				String result1=resultSet1.getString(1);
				
				if(result.equals("attack"))
				{
					response.sendRedirect("attacked.jsp");
				}
				
				else
				{
				String q="select name,path,filekey,user_id, security_check  from userupload where office_id='"+n+"'";
				ps=Connections.con().prepareStatement(q);
				resultSet=ps.executeQuery();
				while(resultSet.next())
				{
					
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr bgcolor=\"white\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td>");
      out.print(resultSet.getString(3));
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(resultSet.getString(4));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(resultSet.getString(1));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<!-- \t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"myFunction('");
      out.print(resultSet.getString(1));
      out.write("')\" value=\"OPEN\"></input>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td><a href=\"Files/all content/");
      out.print(resultSet.getString(1));
      out.write("\" target='_blank' title=\"Click here to Download\"><center>OPEN</center></a></td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(resultSet.getBoolean(5) ? "ON" : "OFF");
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
 
				}
				}
			
		
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("function myFunction(name) {\r\n");
      out.write("//\tvar name=document.getElementsByTagName('button');\r\n");
      out.write("\talert(\"Name=\"+name);\r\n");
      out.write("    var x = document.createElement(\"OBJECT\");\r\n");
      out.write("    x.setAttribute(\"data\", \"Files/all content/\"+name);\r\n");
      out.write("    x.setAttribute(\"width\", \"600\");\r\n");
      out.write("    x.setAttribute(\"height\", \"800\");\r\n");
      out.write("    //document.getElementById(\"demo\").innerHTML = document.body.appendChild(x);\r\n");
      out.write("    document.getElementById(\"demo\").appendChild(x);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<div id=\"demo\"></div>\r\n");
      out.write("\r\n");
      out.write("<a href=\"admin_welcome.jsp\" title=\"Click here to Download\"><center>Back</center></a>\r\n");
      out.write("\t\t\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wrapper line\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col2\">\r\n");
      out.write("\t\t\t\t\t\t<h2>here are some pictures</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wrapper pad_bot1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"left marg_right2\"><a href=\"#\"><img src=\"images/small3.jpg\" alt=\"\" /></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"left marg_right2\"><a href=\"#\"><img src=\"images/small3.jpg\" alt=\"\" /></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"left\"><a href=\"#\"><img src=\"images/small3.jpg\" alt=\"\" /></a></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wrapper pad_bot3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"left marg_right2\"><a href=\"#\"><img src=\"images/small4.jpg\" alt=\"\" /></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"left marg_right2\"><a href=\"#\"><img src=\"images/small5.jpg\" alt=\"\" /></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"left\"><a href=\"#\"><img src=\"images/small4.jpg\" alt=\"\" /></a></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h2>Recent News</h2>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font1\">12.01.2017</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"under\">Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia conquuntur magni dolores eos qui ratione.</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font1\">03.01.2017</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"under\">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam.</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font1\">03.01.2017</p>\r\n");
      out.write("\t\t\t\t\t\t<p>Aliquam commodo felis quis purus blandit convallis. Nunc dolor neque, semper id venenatis porttitor, pulvinar sit amet lacus.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div><div class=\"clear\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div><div class=\"clear\"></div>\r\n");
      out.write("                <div class=\"cont_bot\"></div>\r\n");
      out.write("    <!-- content ends --> \r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("    <div style=\"height:15px\"></div>\r\n");
      out.write("    <!-- bottom begin -->\r\n");
      out.write("    <div id=\"bottom_bot\">\r\n");
      out.write("        <div id=\"bottom\">\r\n");
      out.write("        <div id=\"b_col1\">\r\n");
      out.write("              <h1>Useful Resources</h1>\r\n");
      out.write("                <div style=\"height:10px\"></div>\r\n");
      out.write("                    <ul class=\"spis_bot\">\r\n");
      out.write("                        <li><a href=\"#\">Lorem ipsum dolor sit amet </a></li>\r\n");
      out.write("                        <li><a href=\"#\">Maecenas in magna quis augue</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Ut a mauris nec eros consect</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Nam luctus felis at mauris co </a></li>\r\n");
      out.write("                        <li><a href=\"#\">Aliquam sagittis ligula sit amet </a></li>\r\n");
      out.write("                        <li><a href=\"#\">Quisque sit amet est id urna</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("                <div id=\"b_col2\">\r\n");
      out.write("                    <h1>Contact Information</h1>\r\n");
      out.write("                    <div style=\"height:20px\"></div>\r\n");
      out.write("                    <div style=\"padding-left:10px\">\r\n");
      out.write("                        <div  class=\"box_us\">\r\n");
      out.write("                              <div  class=\"box_us_l\">\r\n");
      out.write("                                <img src=\"images/fish_us1.png\" alt=\"\" />\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div  class=\"box_us_r\">\r\n");
      out.write("                                    <b class=\"lh\">1234 Some Street, Brooklyn, NY 11201</b>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div style=\"clear: both; height:10px;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div  class=\"box_us\">\r\n");
      out.write("                              <div  class=\"box_us_l\">\r\n");
      out.write("                                <img src=\"images/fish_us2.png\" alt=\"\" />\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div  class=\"box_us_r\">\r\n");
      out.write("                                    <b class=\"lh\">Phone:  1(234) 567 8910<br />\r\n");
      out.write("                                        Fax: 1(234) 567 8910\r\n");
      out.write("                                    </b>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div style=\"clear: both; height:10px;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div  class=\"box_us\">\r\n");
      out.write("                              <div  class=\"box_us_l\">\r\n");
      out.write("                                <img src=\"images/fish_us3.png\" alt=\"\" />\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div  class=\"box_us_r\">\r\n");
      out.write("                                    <b class=\"lh\">E-mail: companyname@yahoo.com</b>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div style=\"clear: both; height:10px;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("            <div id=\"b_col3\">\r\n");
      out.write("            \t<h1>Share with Others</h1>\r\n");
      out.write("              \t<div style=\"height:15px\"></div>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><img src=\"images/fu_i1.png\" class=\" fu_i\" alt=\"\" /><a href=\"#\">Subscribe to Blog</a></li>\r\n");
      out.write("                        <li><img src=\"images/fu_i2.png\" class=\" fu_i\" alt=\"\" /><a href=\"#\">Be a fan on Facebook</a></li>\r\n");
      out.write("                        <li><img src=\"images/fu_i3.png\" class=\" fu_i\" alt=\"\" /><a href=\"#\">RSS Feed</a></li>\r\n");
      out.write("                        <li><img src=\"images/fu_i4.png\" class=\" fu_i\" alt=\"\" /><a href=\"#\">Follow us on Twitter</a></li>\r\n");
      out.write("                    </ul>  \r\n");
      out.write("                        \r\n");
      out.write("          </div>\r\n");
      out.write("          \t<div style=\"clear: both; height:20px;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<!-- bottom end --> \r\n");
      out.write("<!-- footer begins -->\r\n");
      out.write("            <div id=\"footer\">\r\n");
      out.write("          \t\tCopyright  2017. <!-- Do not remove -->Designed by <a href=\"http://www.metamorphozis.com/free_templates/free_templates.php\" title=\"Free Website Templates\">Free Website Templates</a><!-- end --><br />\r\n");
      out.write("                <a href=\"#\">Privacy Policy</a> | <a href=\"#\">Terms of Use</a> | <a href=\"http://validator.w3.org/check/referer\" title=\"This page validates as XHTML 1.0 Transitional\"><abbr title=\"eXtensible HyperText Markup Language\">XHTML</abbr></a> | <a href=\"http://jigsaw.w3.org/css-validator/check/referer\" title=\"This page validates as CSS\"><abbr title=\"Cascading Style Sheets\">CSS</abbr></a>\r\n");
      out.write("    </div>\r\n");
      out.write("        <!-- footer ends -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
