/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2017-10-31 19:09:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.sql.*;
import com.Connections.*;

public final class fileViews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Attacker</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

	PreparedStatement ps = null;
	ResultSet resultSet = null;
	Statement st = null;
	PreparedStatement ps1 = null;
	ResultSet resultSet1 = null;
	Statement st1 = null;
	String query = null;

	String officeId = request.getParameter("id");

      out.write("\r\n");
      out.write("<body background=\"images/attack.jpg\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				if (officeId == null || officeId.equals("")) {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h1>NO Cloud Service with this Office Id and Location</h1>\r\n");
      out.write("\t\t\t");

				} else {
					String parameter = request.getParameter("returnParameter");
					if ("attackResponse".equalsIgnoreCase(parameter)) {
						String fileKey = request.getParameter("filekey");
						//String Id =request.getParameter("officeId");
						String status = "A";
						query = "UPDATE itjcc03.adminupload SET status='" + status
								+ "' where filekey='" + fileKey
								+ "' and office_id='" + officeId + "'";
						ps1 = Connections.con().prepareStatement(query);
						ps1.executeUpdate();
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h1>File Has been attacked</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h1>***CLOUD SERVICE GOING TO ATTACKED***</h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h2>\tFiles Of Location Id");
      out.print(officeId);
      out.write("</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\tAdmin Files\r\n");
      out.write("\t\t\t\t<table border=\"2\" bordercolor=\"gray\" width=\"500\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr bgcolor=\"yellow\">\r\n");
      out.write("\t\t\t\t\t\t<td><center>Name/Key</center></td>\r\n");
      out.write("\t\t\t\t\t\t<td><center>File</center></td>\r\n");
      out.write("\t\t\t\t\t\t<td><center>Security Check</center></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						int total = 0;

							String q = "select name,path,filekey, security_check, status from itjcc03.adminupload where office_id='"
									+ officeId + "'";
							ps = Connections.con().prepareStatement(q);
							resultSet = ps.executeQuery();
							while (resultSet.next()) {
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr bgcolor=\"#00000\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(resultSet.getString(3));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(resultSet.getString(1));
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- \t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"myFunction('");
      out.print(resultSet.getString(1));
      out.write("')\" value=\"OPEN\"></input>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if (resultSet.getBoolean(4)) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>Security Enabled</td>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
										if (resultSet.getString(5).equals("A")) {
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>Attacked</td>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"fileViews.jsp?filekey=");
      out.print(resultSet.getString(3));
      out.write("&id=");
      out.print(officeId);
      out.write("&returnParameter=attackResponse\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"Click here to Attck\">Attack</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t");

							}

									}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						}
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/index.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
